### ISSUE TITLE
regexp can be added as a listener

### ISSUE THREAD

**Issue by john-yuan** [Olical/EventEmitter#145] opened 2018-07-11 03:16 UTC
https://github.com/Olical/EventEmitter/blob/1e2c824c0ddce1e73a6b2a8c0ebc912a08a811d6/EventEmitter.js#L122

The `isValidListener ` function returns `true` when RegExp passed in, which allows a RegExp can be added as a valid event listener. But when I try to emit the event, a TypeError thrown. This issue can be reproduced with the code below:

```js
var e = new EventEmitter();

// no error 
e.addListener('regexp', /\s+/);

// emit the regexp event
e.emit('regexp', 'test');
// => Uncaught TypeError: Cannot read property 'apply' of undefined
```

**Comment by Olical** [comment] 2018-07-11 08:13
This isn't a documented use case, the fact that it lets you do this is just an accident really. I could put in an assertion to prevent this but I don't really see much value in it. This sort of thing happens all the time in dynamically typed languages I'm afraid.

Going to close this as it's not a bug in my opinion. Happy to re-open if something is definitely broken though.

**Closed by Olical** 2018-07-11 08:13 UTC
